apiVersion: v1
kind: Service
metadata:
  name: k8s-serv-service
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: k8s-serv
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8080
