project_name: k8s-serv

builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  main: k8s-serv.go
  binary: k8s-serv
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
- env:
  - CGO_ENABLED=0


archive:
  format: tar.gz
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
  - README*
  - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

release:
  draft: false
  github:
    owner: sklevenz
    name: k8s-serv

brew:
  folder: Formula
  caveats: "How to use this binary"
  homepage: "https://github.com/sklevenz/k8s-serv"
  description: "Learning github, travis, go, k8s, docker ..."
  test: |
    system "#{bin}/k8s-serv"
  install: |
    bin.install "k8s-serv"
  github:
    owner: sklevenz
    name: homebrew-skl
