# Default values for k8s-serv-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

namespace: k8s-serv-production

image:
  tag: latest

service:
  port: 8080

ingress:
  enabled: false
